### ISSUE TITLE
Number Of Classes

### ISSUE THREAD

**Issue by SerdarHelli** [facebookresearch/ConvNeXt#110]
I' am trying to run the below code. However, the number of classes doesnt be changed, although I write it on script

!python -m torch.distributed.launch --nproc_per_node=1 main.py \
--model convnext_small --drop_path 0.4 --input_size 224  \
--nb_classes=7 \
--batch_size 32 --lr 4e-3 --update_freq 1  \
--model_ema true --model_ema_eval true --epochs 50 \
--data_path /content/data/ \
--finetune https://dl.fbaipublicfiles.com/convnext/convnext_small_22k_224.pth \
--eval_data_path /content/data/ \
--output_dir /content/

**Comment by jrsykes** [comment]
HI,
I'm having the same problem while trying to train a ConvNeXt tiny model by loading the model from torchvision.models.
Pytorch version: 1.13.0.dev20220624

I use the following two lines of code to load the model and change the number of output nodes:
    
model_ft = models.convnext_tiny(weights=ConvNeXt_Tiny_Weights.DEFAULT)
model_ft.classifier[2].out_features = num_classes

And when I print this layer of the mode I get:
> print(model_ft.classifier[2])
Linear(in_features=768, out_features=2, bias=True)

Which suggests that the change had been made. However, when I train the model, the output has dimensions of batch_size x 1,000:

>batch_size=42
>outputs = model(inputs)
> print(outputs.size())
torch.Size([42, 1000])

Any thoughts on how solve this problem?

Cheers,
Jamie

**Comment by SerdarHelli** [comment]
Thanks <3
