### ISSUE TITLE
pretrained checkpoint loading bug

### ISSUE THREAD

**Issue by congjianting** [facebookresearch/ConvNeXt#12]
Hi,

I found a bug in pretrained checkpoint loading.  

in mmdetection/tools/train.py line: 159 
"model.init_weights()"

in convnext.py line:115 "def init_weights(self, pretrained=None): ",  we need set param "pretrained",
but nowhere i can see this param setting location.

**Comment by s9xie** [comment]
Hi,

This seems to be a version mismatch problem. Did you follow our instruction and use the specific version we provided? 

```
We add ConvNeXt model and config files to Swin Detection. Our code has been tested with commit 6a979e2 
https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/tree/6a979e2164e3fb0de0ca2546545013a4d71b2f7d
```
