### ISSUE TITLE
Detectron2 configs for ConvNeXt

### ISSUE THREAD

**Issue by shivamsnaik** [facebookresearch/ConvNeXt#14]
Hello,
Thanks for releasing the code for ConvNeXt. It helps us big time.
I am currently working on a object detection project with Detectron2 as the framework.

Is there any possibility of configs being released for Detectron2?.

**Comment by s9xie** [comment]
Hi - thank you for your interests. We will be working on D2 + ConvNeXt, and hopefully new results on other datasets too (such as LVIS). While we don't have a concrete timeline, please stay tuned!

**Comment by shivamsnaik** [comment]
Thanks for the quick response. I look forward to the D2 version of results.

**Comment by letmejoin** [comment]
> Hi - thank you for your interests. We will be working on D2 + ConvNeXt, and hopefully new results on other datasets too (such as LVIS). While we don't have a concrete timeline, please stay tuned!

Have you guys concrete timeline?
