### ISSUE TITLE
FP16 settings

### ISSUE THREAD

**Issue by mayizhe01** [facebookresearch/ConvNeXt#16]
Hi, thanks your work.
In semantic segmentation,  about your config-base, large, xlarge, how not to use fp16? There is a bug if you set fp16=false in config directly.

**Comment by HannaMao** [comment]
Thanks a lot for reporting this! Did you see the error `AttributeError: 'AmpState' object has no attribute 'loss_scalers'`? If so, you could disable amp state saving by commenting out line [here](https://github.com/microsoft/unilm/blob/f8f3df80c65eb5e5fc6d6d3c9bd3137621795d1e/beit/semantic_segmentation/mmcv_custom/apex_runner/checkpoint.py#L58). We just pushed a new [commit](https://github.com/facebookresearch/ConvNeXt/commit/f8225752970d6092488f63e7cf27174020f56deb) to our repo which provides the checkpoint.py file with this change as well. You could copy it to the corresponding folder to see if it helps fix the bug you observed. Feel free let us know if you still need help with this!
