### ISSUE TITLE
Custom Data

### ISSUE THREAD

**Issue by EdibHamzaArslan** [facebookresearch/ConvNeXt#17]
Do you will be release anything about for train the model for custom datas?

**Comment by liuzhuang13** [comment]
For image classification, setting `--data_set image_folder` can let you train on a custom dataset. You need to organize the data into the standard PyTorch ImageFolder structure, i.e., each class reside in a separate folder, and set the `--data_path` to the parent folder

**Comment by EdibHamzaArslan** [comment]
ok, thank you.

**Comment by lxwkobe24** [comment]
> 好的谢谢。

您好，请问你训练自己训练集了吗

**Comment by lxwkobe24** [comment]
> 谢谢。

您好，请问你训练自己的数据集了吗

**Comment by EdibHamzaArslan** [comment]
@lxwkobe24 Hi, I start to train my custom dataset on google colab free gpu version. Here is my script

%%shell
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
git clone https://github.com/facebookresearch/ConvNeXt
pip install timm==0.3.2 tensorboardX six

%%shell
cd ConvNeXt/
python -m torch.distributed.launch --nproc_per_node=1 main.py \
--model convnext_tiny --drop_path 0.1 \
--batch_size 8 --lr 4e-3 --update_freq 1 \
--model_ema true --model_ema_eval true \
--data_path my_data_path
--output_dir my_convNext_results

The default epoch number is that 300, and n_classes is 1000. You can change them depend on your data.

My data directory is that:
Data/
       train/
            class1
                 img1.png
                 img2.png
                 img3.png
            class2
            class3
       val/
            class1
                 img1.png
                 img2.png
                 img3.png
            class2
            class3
