### ISSUE TITLE
Question 1x1 conv vs linear

### ISSUE THREAD

**Issue by KatsarosEf** [facebookresearch/ConvNeXt#18]
Congratulations on your work and thanks for sharing! I'd like to naively ask, what is the reason behind implementing 1x1 convs with fully connected layers? I know they are equivalent but I had been thinking the latter is less efficient. 

Thanks in advance!

**Comment by liuzhuang13** [comment]
Thanks for the asking this. It is indeed a decision we've chosen.

We experimented with the two implementation styles: linear layers or 1x1 conv layers for the small "MLP" (1x1 conv-GELU-1x1 conv) part, and it seems using linear layers to operate on permuted (N, H, W, C) tensors is a bit faster in inference (~5% for the whole network) than using conv layers to operate on the (N, C, H, W) tensors. We also tested both approaches in a standalone way (no network, no permutation), in which case the speed difference is even larger. 

Coupling that with the fact that we want to use the original LayerNorm implementation in PyTorch (only supports (N, H, W, C)) format (this is much faster than our custom LN implementation on (N, C, H, W) tensors), we used the linear layer implementation. The speed comparison of course could be different on different platforms. We observed this with PyTorch 1.8.0 and V100 GPUs.

**Comment by KatsarosEf** [comment]
Thank you for your swift response, very detailed of an architectural design build, indeed I only noticed your comment on line 30 :). One last question if you don't mind and I am closing this issue, the choice of GeLU over ReLU is due to some dying neurons observations or was solely chosen based on the related Transformers' papers (BERT, GPT2) as mentionned? Is there a case you experimented with alternatives like Swish?

Many thanks again, all the best to your future works.

**Comment by liuzhuang13** [comment]
The choice of GELU over RELU is in part due to imitating Transformers. Another interesting observation is if we stick to RELU, in the next step "Fewer activations" the training curve becomes a bit strange, despite it can converge to a reasonable level finally. We didn't try activations other than RELU and GELU
