### ISSUE TITLE
Question about layer norm.

### ISSUE THREAD

**Issue by ChenDirk** [facebookresearch/ConvNeXt#19]
Very interesting work, I read the code and paper,  and have a question about the layer normalization in ConvNeXt. Previously, when we use CNN, the Layer norm usually calculate mean and standard deviation of [C, H, W]. (like the description in GN's paper and Pytorch's documentation) But in Transformer structures, such as DETR, they calculate mean and variance for only channel dimension. Did you compare the layer norm between [C] and [C, H, W] in ConvNeXt? Was the layer norm in convNext carefully designed, or just imitate the Transformer architecture?

**Comment by liuzhuang13** [comment]
In my understanding, the original LayerNorm paper is for RNNs, and it is on (N, C) data, where N is batch size, without any spatial or token dimensions. It is straightforward to normalize only across C.

For vision (N,C,H,W) / (N,H,W,C), or NLP (N, L, C), I cannot read from the original LayerNorm paper whether it is suggested to normalize over all dimensions (CHW/HWC, LC) or just the C dimension. GN paper's figure does suggest it's over all dimensions, but I'm not sure. So we followed vision Transformers' implementations in that we only normalize in the C dimension.

**Comment by apache2046** [comment]
I have the same question , Layer Norm in ConvNext like this implemtation
![image](https://user-images.githubusercontent.com/1034542/158553788-86ece4c3-2f6e-49ec-850c-e546239ef0a1.png)

**Comment by ChenDirk** [comment]
> I have the same question , Layer Norm in the ConvNext looks like this ![image](https://user-images.githubusercontent.com/1034542/158553901-769ed32b-6f9e-4cbd-9ec0-7575c16eb9be.png)

You are right, and it is same as layer norm in transformer(N, L, C).  Maybe we can use another name for this kind of normalization in convolution layers(N,C,H,W). Just like, we can also use layer norm function to implement instance norm in Pytorch, but instance norm also has its name. XD
