### ISSUE TITLE
about order of conv and layer norm in downsample_layers

### ISSUE THREAD

**Issue by bamps53** [facebookresearch/ConvNeXt#2]
Hi, thanks for sharing great work!

I have a question about order of conv and layer norm in downsample_layers.
In `stem` there are conv first and then layer norm, but in `downsample_layer` it seems layernorm first.
https://github.com/facebookresearch/ConvNeXt/blob/64aba990d8477fa920685a694df65bdeb302c905/models/convnext.py#L80

It means in downsample_layers there are layers as follows;
- conv2d
- layernorm
- layernorm
- conv2d
- layernorm
- conv2d
- layernorm
- conv2d

Is it intentional design, or just am I misunderstanding something?

**Comment by bamps53** [comment]
Sorry, my bad!
I've misunderstood `self.downsample_layers` is `nn.Sequential` but it's not.

**Comment by F-Barto** [comment]
Sorry to re-open this, but aside from the misunderstanding, I believe the question is valid.

While stem is coherent in regard to [Blocks ](https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py#L15) where we have the ordering conv->norm, in [dowsampling layers you put LayerNorm before convolution.](https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py#L80)

The full path is:

* conv2d 4x4, stride 4
* layernorm
* residual stage 1


- layernorm
- conv2d 2x2, stride 2
- residual stage 2


* layernorm
* conv2d 2x2, stride 2
* residual stage 3


- layernorm
- conv2d 2x2, stride 2
- residual stage 4

Which means that if residual stage 1 converges to identity, we have a layernorm into a layernorm which seems weird to me:
- conv2d 4x4, stride 4
- layernorm
- layernorm
- conv2d 2x2, stride 2

Can you explain this design choice ?
