### ISSUE TITLE
Question about layer_scale_init_value

### ISSUE THREAD

**Issue by jatentaki** [facebookresearch/ConvNeXt#27]
Hello, I noticed your code uses some [multiplication constant](https://github.com/facebookresearch/ConvNeXt/blob/9a7b47bd6a6c156a8018dbd0c3b36303d4e564af/models/convnext.py#L33) which looks like it could be folded directly into the kernel of the preceding linear layer. May I ask what is its use and significance?

**Comment by liuzhuang13** [comment]
Yes, it can be folded in inference/after training. We adopted this technique ("Layer Scale") from [this paper](https://arxiv.org/abs/2103.17239), where it's been shown to facilitate the training of deeper transformers.

**Comment by jatentaki** [comment]
Thanks for your quick answer!
