### ISSUE TITLE
about apex

### ISSUE THREAD

**Issue by oneoneling** [facebookresearch/ConvNeXt#32]
My graphics card is 3070ti, cuda11.3,torch1. 10.1. But I can't compile apex.Do you know how to solve it

The error is as follows：

ERROR: Command errored out with exit status 1: /home/aini/software/anaconda3/envs/cu113_py37_tr110_mm/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b3ie2ccd/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b3ie2ccd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-t1h4adu5/install-record.txt --single-version-externally-managed --compile --install-headers /home/aini/software/anaconda3/envs/cu113_py37_tr110_mm/include/python3.7m/apex Check the logs for full command output.

**Comment by liuzhuang13** [comment]
Hi, our code does not rely on apex nor use apex. We support PyTorch AMP training though.

**Comment by HannaMao** [comment]
Thanks for posting the question! We didn't observe the issue you mentioned when compiling apex. You may want to check the full error log, identify the root cause of the error, and search solutions for that. Please let us know if we could help with anything else.
