### ISSUE TITLE
how to increase the reproducibility ? 

### ISSUE THREAD

**Issue by xyz8129** [facebookresearch/ConvNeXt#34]
run main.py to train, however the accuracy is random and the interval is above 0.5%. Would you like tell me how to improve reproducibility and reduce the accuracy interval? 

I know there are some code in main.py to improve the reproducibility: 
    # fix the seed for reproducibility
    seed = args.seed + utils.get_rank()
    torch.manual_seed(seed)
    np.random.seed(seed)
    cudnn.benchmark = True

**Comment by liuzhuang13** [comment]
I suspect there are some hidden issues if accuracy is random. Can you provide the exact command you run?
