### ISSUE TITLE
convnext is slower than swin ?

### ISSUE THREAD

**Issue by lichun-wang** [facebookresearch/ConvNeXt#37]
I use convnext_tiny as pretrained model to finetune on my own dataset, but  i found convnext_tiny is slower than swin_tiny,  I use 4 nvidia 1080ti.  convnext tiny cost three more times than swin_tiny . But the flops of two model is similar, I don't know why convnext is slower?

**Comment by liuzhuang13** [comment]
That is quite strange. We never observed convnext_tiny is slower than swin_tiny. By timm's latest benchmarking (e.g., https://github.com/rwightman/pytorch-image-models/blob/master/results/benchmark-train-amp-nhwc-pt110-cu113-rtx3090.csv), convnext_tiny is quite faster than swin_tiny.

Are you using the same batch size (per gpu), #epochs and input resolution for both? Are you using AMP for both? Which PyTorch version are you using?

**Comment by lichun-wang** [comment]
> 



> That is quite strange. We never observed convnext_tiny is slower than swin_tiny. By timm's latest benchmarking (e.g., https://github.com/rwightman/pytorch-image-models/blob/master/results/benchmark-train-amp-nhwc-pt110-cu113-rtx3090.csv), convnext_tiny is quite faster than swin_tiny.
> 
> Are you using the same batch size (per gpu), #epochs and input resolution for both? Are you using AMP for both? Which PyTorch version are you using?

I'm also confused .  The codes for training are same . The hyper-parameters are same too(include batchsize).  I just only changed  pretrained model from swin_tiny to convnext . I didn't use AMP .  I download swin_tiny and convnext_tiny from timm's url.  My pytorch version is 1.10.0.

**Comment by liuzhuang13** [comment]
Which training code are you using? Is it possible for us to look at the code and exact command?

**Comment by lichun-wang** [comment]
> 
I use the official code from pytorch tutorials to test , the link is :https://github.com/pytorch/tutorials/blob/master/beginner_source/transfer_learning_tutorial.py

and **I change line253-257 to load swin_tiny and convnext_tiny**, loading codes are as below:

```
# swin_tiny
model_ft = timm.create_model('swin_tiny_patch4_window7_224', pretrained=True)
model_ft.head = nn.Linear(in_features=model_ft.head.in_features, out_features=3)
model_ft = model_ft.to(device)

# convnext_tiny
model_ft = timm.create_model('convnext_tiny', pretrained=True)
model_ft.head.fc = nn.Linear(in_features=model_ft.head.fc.in_features, out_features=3)
model_ft = model_ft.to(device)
```


My testing dataset has about 2W images. and  I test on one nvidia 1080ti.   batchsize = 32. 

The testing result show  that :  resnet50 cost 108s/epoch;   swin_tiny cost 166s/epoch;  convnext_tiny cost 556s/epoch.

Can you help me to test on the pytorch official code?

**Comment by developer0hye** [comment]
@lichun-wang 

Did you set `cudnn.benchmark` to True?

If you don't set this to True, backward speed will be very slow.

```python
import torch.backends.cudnn as cudnn
cudnn.benchmark = True
```

**Comment by lichun-wang** [comment]
> @lichun-wang
> 
> Did you set `cudnn.benchmark` to True?
> 
> If you don't set this to True, backward speed will be very slow when you train the model including depthwise convolutional layer.
> 
> ```python
> import torch.backends.cudnn as cudnn
> cudnn.benchmark = True
> ```
I test this code , but it didn't change the speed. It seems to be not useful.

**Comment by s9xie** [comment]
Have you tried our code / pre-trained models rather than using the timm ones? What timm version are you using? You can try a different pytorch version (e.g. downgrade it to 1.7.1).

Since you are using the timm code, I suspect this is an env + timm issue. Closing this for now as it is not directly related to this code repo. Feel free to reopen it if you experience a similar behavior using our code.

**Comment by lichun-wang** [comment]
> Have you tried our code / pre-trained models rather than using the timm ones? What timm version are you using? You can try a different pytorch version (e.g. downgrade it to 1.7.1).
> 
> Since you are using the timm code, I suspect this is an env + timm issue. Closing this for now as it is not directly related to this code repo. Feel free to reopen it if you experience a similar behavior using our code.

@s9xie   Yes, you are right. I use your official pre-trained model , the speed is more faster than the timm ones . After using your  official code , the speed of swin_tiny and convnext_tiny is similar.

Thank you very much !   

Happy Chinese New Year !

**Comment by Zhiwei-Zhai** [comment]
I have a similar issue. When using the convernext tiny from torchvision, it cost 3 second per iteration. 
```
model = torchvision.models.convnext_tiny(pretrained=pretrained)
```
However, when use this official model, it is much faster, like 3 iteration per second.
```
model = convnext_tiny(pretrained=pretrained, in_22k=False)
```
