### ISSUE TITLE
What is the batch size for training COCO dataset?

### ISSUE THREAD

**Issue by songyuc** [facebookresearch/ConvNeXt#4]
Hi, guys,
I want to know about the batch size for training the COCO dataset, which seems not to have been revealed in the [paper](https://arxiv.org/pdf/2201.03545.pdf).
And I am wondering whether the batch size of COCO is set in [../_base_/datasets/coco_instance.py](https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/configs/convnext/mask_rcnn_convnext_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco_in1k.py#:~:text=%27../_base_/datasets/coco_instance.py%27)?

Your answer and guide will be appreciated!

**Comment by s9xie** [comment]
We will add the details in the paper. Thanks for pointing that out.  But basically we followed Swin and mmdet (you can find those default confit in the base config files in Swin/mmdet repos, following our provided instructions). The detection experiments are trained with single node, 8 GPU and samples_per_gpu=2.

**Comment by songyuc** [comment]
Thanks sincerely for your answer!
