### ISSUE TITLE
Question: Why no activation function in the Stem layer?

### ISSUE THREAD

**Issue by Kait0** [facebookresearch/ConvNeXt#42]
Hi,

I was curious why you don't use an activation function in the stem layer:
```
stem = nn.Sequential(
            nn.Conv2d(in_chans, dims[0], kernel_size=4, stride=4),
            LayerNorm(dims[0], eps=1e-6, data_format="channels_first")
        )
```
I think the standard res net uses an activation function in their stem layer (before the maxpool).
I couldn't find in the paper when you changed that.
Is there some intuition why this design choice makes sense?

**Comment by liuzhuang13** [comment]
Hi, 

Yes, we borrowed the much simpler non-overlapping convolution (aka "patch embedding") in (Swin-)Transformers. There is no activation in that design so we did not use it either. The central question we ask in paper is how design choices in Transformers impact the performance of a ConvNet, so we did not try other choices. Without multiple layers and activations, the single layer even gives a little improvement. Together with its simplicity, we chose to keep this. The empirical experience gained here is overlapping operations in early layers is not as needed as perceived.
