### ISSUE TITLE
Question: Small initial weights

### ISSUE THREAD

**Issue by Khoa-NT** [facebookresearch/ConvNeXt#44]
Hi, 

Thank you for sharing the code.
I saw you are using  `trunc_normal_(m.weight, std=.02)` in the [Block](https://github.com/facebookresearch/ConvNeXt/blob/main/semantic_segmentation/backbone/convnext.py#L114) module.

I think it makes the weights are too small and hard to train the model.
And the values are may smaller after multiplied with the [gamma](https://github.com/facebookresearch/ConvNeXt/blob/main/semantic_segmentation/backbone/convnext.py#L39)

Is there any reason? Why you didn't keep the default initialization?

**Comment by liuzhuang13** [comment]
Hi,

We followed typical Transformer initializations for linear layers (i.e., 1x1 convs), like that from [timm's ViT](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py) or [Swin Transformers](https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py). I believe this all is inherited from Transformers in NLP.

In practice, we observed little to no influence to the final accuracy if we use PyTorch's default init for conv layers. We think it would be simpler to use the same initialization for all layers.
