### ISSUE TITLE
Broken link for object detection installation and dataset preparation.

### ISSUE THREAD

**Issue by Michelvl92** [facebookresearch/ConvNeXt#46]
In [object_detection](https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection) you refer to [README.md](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md) for installation and dataset preparation instructions. 

But the link in [README.md](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md) : get_started.md is broken. Could you update the object detection installation and dataset preparation readme?

**Comment by liuzhuang13** [comment]
Hi,

I think it's due to an update in the mmdetection repo. Here is the supposed linked place: https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md
