### ISSUE TITLE
Why can not reproduce the acc on best-ema model for test_acc1_ema？

### ISSUE THREAD

**Issue by becauseofAI** [facebookresearch/ConvNeXt#47]
I eval the best-ema model on my custom dataset, but the value of result is test_acc1 not test_acc1_ema that recorded in the log file. Who can tell me how to reproduce the test_acc1_ema with best-ema model？

**Comment by liuzhuang13** [comment]
Hi,

The test_acc1_ema variable is useful only when ema is used in training. We put the ema model saved in training to a checkpoint that has 'model' as the only key, so it would behave the same as a non-ema model in evaluation.
