### ISSUE TITLE
how to convert the saved model to inference model?

### ISSUE THREAD

**Issue by becauseofAI** [facebookresearch/ConvNeXt#48]
The size of training saved model of convnext_base is 1.4G, how to convert it to 89M as the repo. reported? I try to convert it using ```torch.save(model.state_dict(), 'convnext-b-224-model-best.pth')``` but get 335M.

**Comment by liuzhuang13** [comment]
Hi,

89M is the number of parameters, not the disk storage size. Each parameter takes 4 bytes you'll get 89 * 4 ~= 335M model size.
