### ISSUE TITLE
COCO training: _base_/datasets/coco_instance.py" does not exist

### ISSUE THREAD

**Issue by Michelvl92** [facebookresearch/ConvNeXt#49]
The file `/ConvNeXt/object_detection/configs/_base_/datasets/coco_instance.py` does not exist.

Would this file be provided, should I use the one from mmdection: [mmdetection/blob/master/configs/_base_/datasets/coco_detection.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/_base_/datasets/coco_detection.py), should I use the one from Swin-V [SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/_base_/datasets/coco_detection.py)](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/master/configs/_base_/datasets/coco_detection.py), or implement myself?

**Comment by HannaMao** [comment]
You could use the one from the Swin codebase. You could follow the instructions here https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection to add ConvNeXt model and config files to Swin Detection codebase. Our code has been tested with commit `6a979e2`. Please let us know if you have any other questions.
