### ISSUE TITLE
some files don't exist.

### ISSUE THREAD

**Issue by congjianting** [facebookresearch/ConvNeXt#5]
Hi, 

i found some files not existing in master branch, such as, 

"from .checkpoint import load_checkpoint"

**Comment by MengzhangLI** [comment]
You should install beit first, this repo is developed upon [beit](https://github.com/microsoft/unilm/tree/master/beit).

Or you just need to borrow those files [here](https://github.com/microsoft/unilm/tree/master/beit/semantic_segmentation/mmcv_custom) to your repo.

**Comment by congjianting** [comment]
@MengzhangLI  thanks for your reply, i will try.
