### ISSUE TITLE
Default image input size pre-trained COCO models?

### ISSUE THREAD

**Issue by Michelvl92** [facebookresearch/ConvNeXt#53]
What is the image input size of the pre-trained coco models? Is it correct that this is 1280 x 800 as stated in the paper in the caption of Table 3?

To improve the GFLOPS, I prefer to use an input size of 640 x 640 when finetuning on my custom dataset. How does this affect the model's detection performance?

**Comment by HannaMao** [comment]
ConvNeXt model is not restricted by image size. In the paper, we use 1280x800 when calculating FLOPs. We adopted multi-scale training when fine-tuning COCO models, e.g. [config](https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/configs/convnext/cascade_mask_rcnn_convnext_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco_in1k.py#L95) for base 1k model. Please let us know if you have any other questions.

**Comment by Michelvl92** [comment]
@HannaMao thank you for your reply. I understand that due to multi-scale training the ConvNext model is not restricted. Although I am curious what is de maximal input size, or in other words what is the maximal resolution an img is downsampled to during training (is 800 x1333 correct?). To which resolution are the coco images downscaled when testing for MS COCO mAP?

My problem is that when finetuning a ConvNeXt large model with default settings, on a dataset (which contains many small objects) results in an extremely low COCO mAP, (e.g. 0.009) while training the same dataset on Swin-Transformer model with default settings, results in an mAP of an "expected" range (45. - 65 mAP). Or there should be more wrong? It almost looks like the pre-trained model weights are not (correctly) loaded with a dataset with 1 class.
