### ISSUE TITLE
ConvNeXt-S and ConvNeXt-T models pretrained on ImageNet-22k

### ISSUE THREAD

**Issue by CanyonWind** [facebookresearch/ConvNeXt#54]
Hi, this is certainly great work, and thank you for the contribution!

Models pretrained on ImageNet-22k outperform the ones without significantly. Wonder whether it's possible for you guys to release the **ConvNeXt-S&T** models that have been **pretrained on ImageNet-22k**? If possible, it would motivate lots of on-device downstream tasks to integrate ConvNeXt as the backbone.  I've tried the current ImageNet-1k trained models with panoptic segmentation and it works like a charm. ConvNext-S&T pretrained with ImageNet-22k will be greatly appreciated. Thanks!

**Comment by liuzhuang13** [comment]
Hi,

Thanks for your suggestion. We will release them hopefully within next week.

**Comment by CanyonWind** [comment]
Thank you for the fast action, look forward to the release.

**Comment by chuong98** [comment]
Hi @liuzhuang13 , do you have any update on uploading model Tiny & Small with ImageNet 22k Pretrained?
Thank you.

**Comment by CanyonWind** [comment]
@liuzhuang13 I'm kindly following up on the pretraining progress. Wonder whether there is any difficulty that the community could help with? Any updates would be appreciated.

**Comment by liuzhuang13** [comment]
Hi all,

Sorry for the delay... In our new updated arxiv paper we included the results for tiny and small with 22k pretraining. The models will be released very shortly.

**Comment by liuzhuang13** [comment]
Hi all,

We have added the models to our readme page. Check them out!
