### ISSUE TITLE
Evaluation in own classes

### ISSUE THREAD

**Issue by esalagran** [facebookresearch/ConvNeXt#55]
I understand that convNeXt with the 22k imagenet is aimed to be a zero-shot algorithm. Is there any way to evaluate the model only on the classes I am interested to?

**Comment by liuzhuang13** [comment]
Hi,

You can select the subset of outputs you are interested in, following this file https://dl.fbaipublicfiles.com/convnext/label_to_words.json

**Comment by liuzhuang13** [comment]
Closing this for now. Feel free to reopen if you have questions

**Comment by jiyuanyu** [comment]
您好，请问我想测试自己的数据集，应该怎么修改代码？
