### ISSUE TITLE
Hello I have an initial problem

### ISSUE THREAD

**Issue by iamwic** [facebookresearch/ConvNeXt#57]
Traceback (most recent call last):
  File "C:/Users/janice/Desktop/covnet/ConvNeXt-main/main.py", line 477, in <module>
    main(args)
  File "C:/Users/janice/Desktop/covnet/ConvNeXt-main/main.py", line 205, in main
    utils.init_distributed_mode(args)
  File "C:\Users\janice\Desktop\covnet\ConvNeXt-main\utils.py", line 329, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "C:\Users\janice\anaconda3\envs\covnet\lib\site-packages\torch\distributed\distributed_c10d.py", line 503, in init_process_group
    _update_default_pg(_new_process_group_helper(
  File "C:\Users\janice\anaconda3\envs\covnet\lib\site-packages\torch\distributed\distributed_c10d.py", line 597, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
Killing subprocess 14712
Traceback (most recent call last):
  File "C:\Users\janice\anaconda3\envs\covnet\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\janice\anaconda3\envs\covnet\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\janice\anaconda3\envs\covnet\lib\site-packages\torch\distributed\launch.py", line 340, in <module>
    main()
  File "C:\Users\janice\anaconda3\envs\covnet\lib\site-packages\torch\distributed\launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "C:\Users\janice\anaconda3\envs\covnet\lib\site-packages\torch\distributed\launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\janice\\anaconda3\\envs\\covnet\\python.exe', '-u', 'C:/Users/janice/Desktop/covnet/ConvNeXt-main/main
.py', '--local_rank=0', '--model', 'convnext_tiny', '--drop_path', '0.1', '--batch_size', '128', '--lr', '4e-3', '--update_freq', '4', '--model_ema', 'true
', '--model_ema_eval', 'true', '--data_path', 'C:/Users/janice/Desktop/covnet/train_val_test/training', '--output_dir', 'C:/Users/janice/Desktop/covnet/res
ults']' returned non-zero exit status 1.

I have no idea about this error

**Comment by iamwic** [comment]
Hello thank you for solving my question.
I'm starting to try training my custom data, but I got this kind of error

RuntimeError: Error(s) in loading state_dict for ConvNeXt:
        size mismatch for head.weight: copying a param with shape torch.Size([1000, 768]) from checkpoint, the shape in current model is torch.Size([2, 768
]).
        size mismatch for head.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([2]).
Killing subprocess 23428

how could I solve it?

**Comment by liuzhuang13** [comment]
You need to set -nb_classes to your custom number of classes

**Comment by iamwic** [comment]
python -m torch.distributed.launch --nproc_per_node=1 C:/Users/janice/Desktop/covnet/ConvNeXt-main/main.py --model convnext_tiny --drop_path 0.1 --batch_size 32 --lr 4e-3 --update_freq 8 --model_ema true --model_ema_eval true --data_path C:/Users/janice/Desktop/covnet/train_val_test/training/train --eval_data_path C:/Users/janice/Desktop/covnet/train_val_test/training/val --output_dir C:/Users/janice/Desktop/covnet/results --nb_classes 2 --data_set 'image_folder'

**Comment by liuzhuang13** [comment]
From the command I don't see you are loading from other models, but the error you gave seems to be for that reason. It seems you are loading a 1000-class pretrained model to your 2-class model

**Comment by Basheeralwaely** [comment]
Hi, I have the same issue. Did you manage to find where the new saved model with 2 outputs is located?
For me, I followed the same training steps on CIFAR10, but when I use 

!python main.py --model convnext_tiny --eval true \
--resume C:/Users/xxx/xxx/data/checkpoint-best.pth \
--input_size 32 --drop_path 0.2 \
--nb_classes 10 \
--data_path C:/Users/xxx/xxx/data/cifar10

I got this error, "size mismatch for head.weight: copying a param with shape torch.Size([10, 768]) from checkpoint, the shape in current model is torch.Size([1000, 768])."

**Comment by liuzhuang13** [comment]
Did you set `pretrained=True` in `main.py` model creation here https://github.com/facebookresearch/ConvNeXt/blob/main/main.py#L280? That one is supposed to be False. Otherwise it will load a 1000 class ImageNet-1K model, which contradicts your `nb_classes` which is 2 or 10.

If you use the `--finetune` flag to load pretrained model instead, it will automatically discard the last layer if the number of classes doesn't match

**Comment by iamwic** [comment]
I set pretrained=False and I didn't use the --finetune, if I force to use it, what should I put in --finetune ?

**Comment by liuzhuang13** [comment]
I suggest you print out your `nb_classes` variable at different places and know into what model is actually be loaded. Then it should be clear what the error is about. 

> I set pretrained=False and I didn't use the --finetune, if I force to use it, what should I put in --finetune ?
The url or path to the pretrained checkpoint should be in `--finetune`.

**Comment by liuzhuang13** [comment]
Or you could be using the default `--auto_resume` flag to load an existing model, which has 1000 classes, but your current model has 2.

**Comment by iamwic** [comment]
Hello, I have another question. If I force to turn off all the data augmentation, I had change these variables
--mixup 0 --cutmix 0 --reprob 0 --color_jitter 0 --aa "original" --smoothing 0
Is there still any other variable I should change?

**Comment by liuzhuang13** [comment]
I think that is all the "advanced" data augmentations but you'll still have basic ones like cropping and flipping, which come from the "create_transform" function of timm (imported in our dataset.py).
