### ISSUE TITLE
where are these files:  ./_base_/models/cascade_mask_rcnn_convnext_fpn.py',     '../_base_/datasets/coco_instance.py',     '../_base_/schedules/schedule_1x.py', 

### ISSUE THREAD

**Issue by Williamlizl** [facebookresearch/ConvNeXt#62]
where are these files:
`./_base_/models/cascade_mask_rcnn_convnext_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', `

**Comment by Williamlizl** [comment]
> Hi,
> 
> Our object detection code relies on Swin Transformer's code. You need to install Swin's codebase first and add our files there. Please follow the instructions [here](https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection#getting-started)

Yes, you mean I install Swin's codebase and then add all these ConvNeXt files to that codebase?

**Comment by maxisawesome** [comment]
@Williamlizl That's what we did. basically, clone both and then `cp -R` each folder under "object_detection" from this repo into the SwinTransformer Repo. Unfortunately, we hit this problem issue #67 right after that. 

I'd like to note that install instruction end up pointing you to an install markdown file in SwinTransformer's repo that 404s, essentially meaning this repo doesn't have install instructions.

**Comment by HannaMao** [comment]
> @Williamlizl That's what we did. basically, clone both and then `cp -R` each folder under "object_detection" from this repo into the SwinTransformer Repo. Unfortunately, we hit this problem issue #67 right after that.
> 
> I'd like to note that install instruction end up pointing you to an install markdown file in SwinTransformer's repo that 404s, essentially meaning this repo doesn't have install instructions.

Sorry to hear about this!! Will you be able to open this [link](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md)?

**Comment by maxisawesome** [comment]
I am! I'm not able to open the link on that page relevant to installation, which can be found [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md#installation).

I think [this](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md) is the right link.

**Comment by HannaMao** [comment]
> I am! I'm not able to open the link on that page relevant to installation, which can be found [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md#installation).
> 
> I think [this](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md) is the right link.

This is the right one! Did it help you resolve the issue? 
I think these two lines might help
> pip install -r requirements/build.txt
python setup.py develop

**Comment by joeyslv** [comment]
> > I am! I'm not able to open the link on that page relevant to installation, which can be found [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md#installation).
> > I think [this](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md) is the right link.
> 
> This is the right one! Did it help you resolve the issue? I think these two lines might help
> 
> > pip install -r requirements/build.txt
> > python setup.py develop

i also have the same error after i do `pip install -r requirements/build.txt` and `python setup.py develop`
the error  :
gpu_ids = range(0, 1)

```
Traceback (most recent call last):
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\detectors\cascade_rcnn.py", line 28, in __init__
    init_cfg=init_cfg)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\detectors\two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ConvNeXt is not in the models registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 161, in main
    test_cfg=cfg.get('test_cfg'))
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\builder.py", line 59, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "CascadeRCNN: 'ConvNeXt is not in the models registry'"
PS E:\Object-Detection\Github\Swin-Transformer-Object-Detection-master> 
```
is there other way to solve it? help plz !QAQ

**Comment by HannaMao** [comment]
> > > I am! I'm not able to open the link on that page relevant to installation, which can be found [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/README.md#installation).
> > > I think [this](https://github.com/open-mmlab/mmdetection/blob/master/docs/en/get_started.md) is the right link.
> > 
> > 
> > This is the right one! Did it help you resolve the issue? I think these two lines might help
> > > pip install -r requirements/build.txt
> > > python setup.py develop
> 
> i also have the same error after i do `pip install -r requirements/build.txt` and `python setup.py develop` the error : gpu_ids = range(0, 1)
> 
> ```
> Traceback (most recent call last):
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 52, in build_from_cfg
>     return obj_cls(**args)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\detectors\cascade_rcnn.py", line 28, in __init__
>     init_cfg=init_cfg)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\detectors\two_stage.py", line 32, in __init__
>     self.backbone = build_backbone(backbone)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\builder.py", line 20, in build_backbone
>     return BACKBONES.build(cfg)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 45, in build_from_cfg
>     f'{obj_type} is not in the {registry.name} registry')
> KeyError: 'ConvNeXt is not in the models registry'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 187, in <module>
>     main()
>   File "tools/train.py", line 161, in main
>     test_cfg=cfg.get('test_cfg'))
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmdet\models\builder.py", line 59, in build_detector
>     cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "D:\App\anaconda\envs\swin-t\lib\site-packages\mmcv\utils\registry.py", line 55, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> KeyError: "CascadeRCNN: 'ConvNeXt is not in the models registry'"
> PS E:\Object-Detection\Github\Swin-Transformer-Object-Detection-master> 
> ```
> 
> is there other way to solve it? help plz !QAQ

Do you by chance also include this file https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/__init__.py? I don't think there is any special step needed to let it recognize ConvNeXt model.

**Comment by HannaMao** [comment]
> @Williamlizl That's what we did. basically, clone both and then `cp -R` each folder under "object_detection" from this repo into the SwinTransformer Repo. Unfortunately, we hit this problem issue #67 right after that.
> 
> I'd like to note that install instruction end up pointing you to an install markdown file in SwinTransformer's repo that 404s, essentially meaning this repo doesn't have install instructions.

Please refer to https://github.com/facebookresearch/ConvNeXt/issues/81#issue-1174175800 for discussions.
