### ISSUE TITLE
u-net convnext

### ISSUE THREAD

**Issue by seekingdeep** [facebookresearch/ConvNeXt#63]
Hi there,
it's great to see that CNN's still are showing great potential, though the question is, can these modifications be applied to a u-net, and what are the effects and improvements shown.

**Comment by s9xie** [comment]
It should be fine to extend convnext to a U-Net structure. On the decoder end, it might make sense to make it asymmetric - you probably don't want a depthwise 7x7 deconv, but 2x2 stride deconv might be okay.
