### ISSUE TITLE
Object Detection implementation issues

### ISSUE THREAD

**Issue by cydiachen** [facebookresearch/ConvNeXt#64]
Thank you for your excellent work. I have one concern that in your MMDet implementation, https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/convnext.py does not have any implementation of loading pretrained IMAGENET_pretrain. Is that a missing feature?

**Comment by HannaMao** [comment]
It can load pretrained models with code [here](https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/convnext.py#L134). Did you meet any issues loading your pretrained models?

**Comment by cydiachen** [comment]
> It can load pretrained models with code [here](https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/mmdet/models/backbones/convnext.py#L134). Did you meet any issues loading your pretrained models?

Hello, I want to train our network with convnext backbone, since the __init__ function does not have any entry for loading pretrained imagenet weights, I want to know the approach to load path with local path. 
Ex. 
![image](https://user-images.githubusercontent.com/26337720/153784530-df876ade-c5f4-406b-8312-d69cf8f3adaa.png)
It has init_cfg to give checkpoint path.

**Comment by HannaMao** [comment]
You can follow the instruction [here](https://github.com/facebookresearch/ConvNeXt/tree/main/object_detection#training) to provide pretrained model weights.
