### ISSUE TITLE
您好，想问一下这段数据增强，如果我不想要的话，请问要怎么去写，因为好像它会跳转到timm.data,我不想要RandomResizedCropAndInterpolation这个操作，您好，感谢您的回答

### ISSUE THREAD

**Issue by lxwkobe24** [facebookresearch/ConvNeXt#65]
transform = create_transform(
            input_size=args.input_size,
            is_training=True,
#             color_jitter=args.color_jitter,
#             auto_augment=args.aa,
#             interpolation=args.train_interpolation,
#             re_prob=args.reprob,
#             re_mode=args.remode,
#             re_count=args.recount,
            mean=mean,
            std=std,
        )

**Comment by liuzhuang13** [comment]
You may write your own transform, for example, with only mean and std. For exmaple, following this: https://github.com/pytorch/examples/blob/main/imagenet/main.py
