### ISSUE TITLE
Typo in Fig.3 (b)

### ISSUE THREAD

**Issue by youngwanLEE** [facebookresearch/ConvNeXt#66]
Hi,

In Figure.3, (b) illustrates the inverted bottleneck where the third block has the channel: 96 -> 384.

But, I think the channel information is the opposite: 384 -> 96 because this block is the inverted block.

Please correct me if my thought was wrong.

**Comment by liuzhuang13** [comment]
Hi,

Thanks for your inputs. Yes this indeed a typo. We'll correct this in the paper's next version.
