### ISSUE TITLE
how to use syncbn when training with more than 1 card?

### ISSUE THREAD

**Issue by clw5180** [facebookresearch/ConvNeXt#68]
It seems that ConvNext use LN, and can't change to syncbn

**Comment by liuzhuang13** [comment]
Hi,

I think you can replace LN with syncbn. The way to write the code should be the same as syncbn in any other models. In practice, for imagenet classification, syncbn or normal bn shouldn't make a difference since the batch size is large enough for each gpu.

**Comment by clw5180** [comment]
> Hi,
> 
> I think you can replace LN with syncbn. The way to write the code should be the same as syncbn in any other models. In practice, for imagenet classification, syncbn or normal bn shouldn't make a difference since the batch size is large enough for each gpu.

Thanks to reply, I'm training object detection model, and I will try it.
