### ISSUE TITLE
have you try convnext-t with mask rcnn 1x schedule? or can you provide the 3x log.

### ISSUE THREAD

**Issue by czczup** [facebookresearch/ConvNeXt#69]
Thank you for your excellent work!
Have you try convnext-t with mask rcnn 1x schedule? or can you provide the 3x log.

**Comment by czczup** [comment]
I try to train convnext-t with mask rcnn 1x schedule,
the log is:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/23737120/154419056-a384bfde-08c0-478f-b358-fc7fda291a4b.png">
Is asking these indices please regular? It seems to converge a little bit slowly

**Comment by czczup** [comment]
My config
```
# Copyright (c) Meta Platforms, Inc. and affiliates.

# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.


_base_ = [
    '../_base_/models/mask_rcnn_convnext_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

model = dict(
    backbone=dict(
        in_chans=3,
        depths=[3, 3, 9, 3],
        dims=[96, 192, 384, 768],
        drop_path_rate=0.4,
        layer_scale_init_value=1.0,
        out_indices=[0, 1, 2, 3],
        pretrained="pretrained/convnext_tiny_1k_224_.pth",
    ),
    neck=dict(in_channels=[96, 192, 384, 768]))

optimizer = dict(constructor='LearningRateDecayOptimizerConstructor', _delete_=True, type='AdamW',
                 lr=0.0001, betas=(0.9, 0.999), weight_decay=0.05,
                 paramwise_cfg={'decay_rate': 0.95,
                                'decay_type': 'layer_wise',
                                'num_layers': 6})
```

**Comment by Williamlizl** [comment]
> Thank you for your excellent work! Have you try convnext-t with mask rcnn 1x schedule? or can you provide the 3x log.

Hi, how you could run the model? which files I should add to the Swin-Transformer-Object-Detection files?

**Comment by czczup** [comment]
> > Thank you for your excellent work! Have you try convnext-t with mask rcnn 1x schedule? or can you provide the 3x log.
> 
> Hi, how you could run the model? which files I should add to the Swin-Transformer-Object-Detection files?

I add these files to official mmdetection directly, including the `convnext.py`, `mask_rcnn_convnext_fpn.py`, `layer_decay_optimizer_constructor.py`, configs. Note that you also should update the `__init__.py`

**Comment by Williamlizl** [comment]
> > > Thank you for your excellent work! Have you try convnext-t with mask rcnn 1x schedule? or can you provide the 3x log.
> > 
> > 
> > Hi, how you could run the model? which files I should add to the Swin-Transformer-Object-Detection files?
> 
> I add these files to official mmdetection, including the `convnext.py`, `mask_rcnn_convnext_fpn.py`, `layer_decay_optimizer_constructor.py`, configs. Note that you also should update the `__init__.py`

layer_decay.py is in the path
‘/ConvNeXt/object_detection/mmcv_custom/layer_decay_optimizer_constructor.py`
where should I add the .py to mmdetection file?

**Comment by HannaMao** [comment]
> I try to train convnext-t with mask rcnn 1x schedule, the log is: <img alt="image" width="980" src="https://user-images.githubusercontent.com/23737120/154419723-641bdc2f-8501-445f-9b84-3c3cd252919e.png"> <img alt="image" width="981" src="https://user-images.githubusercontent.com/23737120/154419056-a384bfde-08c0-478f-b358-fc7fda291a4b.png"> Is asking these indices please regular? It seems to converge a little bit slowly

The `missing keys` and `unexpected keys` look good to me. what do you mean by "these indices"?

**Comment by HannaMao** [comment]
> 

For ConvNeXt-tiny with mask rcnn 1x, you probably don't need such high drop path rate. You can try smaller dp, e.g. 0.1/0.2, for your experiments

**Comment by czczup** [comment]
> > 
> 
> For ConvNeXt-tiny with mask rcnn 1x, you probably don't need such high drop path rate. You can try smaller dp, e.g. 0.1/0.2, for your experiments

Thank you very much for your reply, this is my log of convnext-t + mask rcnn 1x schedule w/o ms.
I train it with drop-path-rate = 0.1. This result seems to be a bit low, is this normal?
Could you please provide the log of 3x schedule?
<img width="978" alt="image" src="https://user-images.githubusercontent.com/23737120/154607228-e4132c30-12a9-4421-a3fc-7eaab60598c0.png">

**Comment by HannaMao** [comment]
We plan to share all logs together soon. Let me run one mask rcnn 1x and share the results with you.

**Comment by czczup** [comment]
> We plan to share all logs together soon. Let me run one mask rcnn 1x and share the results with you.
Thanks very much!

**Comment by czczup** [comment]
> Here are results and log from a single run <img alt="image" width="1386" src="https://user-images.githubusercontent.com/16569221/154787515-2756b03b-00b9-4f28-a4f2-1f1a3dafcb8b.png"> I used dp 0.1. Other hyperparameters are the same as [here](https://github.com/facebookresearch/ConvNeXt/blob/main/object_detection/configs/convnext/mask_rcnn_convnext_tiny_patch4_window7_mstrain_480-800_adamw_3x_coco_in1k.py). It is likely further tuning the hyperparameters could produce better results.

Thanks!
