### ISSUE TITLE
How to train ConvNeXt-tiny using an input size 384 ?

### ISSUE THREAD

**Issue by K-H-Ismail** [facebookresearch/ConvNeXt#72]
Hello,
I want to train ConvNeXt-tiny from scratch using an input size of 384 instead of 224. In your paper there is mention to input size 384 only for ConvNeXt-B/L/XL, can I just use the following script for ConvNeXt-tiny and change the input_size option or is there other parameters to change ? 
```
python run_with_submitit.py --nodes 4 --ngpus 8 \
--model convnext_tiny --drop_path 0.1 \
--batch_size 128 --lr 4e-3 --update_freq 1 --input_size 384\
--model_ema true --model_ema_eval true \
--data_path /path/to/imagenet-1k \
--job_dir /path/to/save_results 

```

Thanks again for the code release !

**Comment by liuzhuang13** [comment]
Hi,

Note that we didn't try training from scratch with 384 in our paper. All 384 results are fine-tuned from 224 trained models. We will release a convnext-tiny pretrained on 224 (IN22k) then fine-tuend on 384(IN1k) soon.

**Comment by K-H-Ismail** [comment]
Hello,

I didn't notice it in the appendix, my bad ! Thanks for this clarification.
