### ISSUE TITLE
ObjectDetection: Which MMdetection version of this object detection demo is used?

### ISSUE THREAD

**Issue by chfguo** [facebookresearch/ConvNeXt#76]

**Comment by HannaMao** [comment]
We used version 2.11.0 for mmdet.

**Comment by chfguo** [comment]
Thanks for you reply. Another question needs your help. The object_detection/mmcv_custom/__init__.py needs function <load_checkpoint>, but I did not find it. There is only <save_checkpoint> in object_detection/mmcv_custom/runner/checkpoint.py

**Comment by HannaMao** [comment]
As described in `README`, we add ConvNeXt model and config files to [Swin Detection](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/tree/6a979e2164e3fb0de0ca2546545013a4d71b2f7d). Our code has been tested with commit 6a979e2. You can find the checkpoint.py file [here](https://github.com/SwinTransformer/Swin-Transformer-Object-Detection/blob/6a979e2164e3fb0de0ca2546545013a4d71b2f7d/mmcv_custom/checkpoint.py).
