### ISSUE TITLE
pretrained = None?

### ISSUE THREAD

**Issue by Williamlizl** [facebookresearch/ConvNeXt#78]
`model = dict(
    type='CascadeRCNN',
    pretrained=None,
    backbone=dict(
        type='ConvNeXt',
        in_chans=3,
        depths=[3, 3, 9, 3], 
        dims=[96, 192, 384, 768], 
        drop_path_rate=0.2,
        layer_scale_init_value=1e-6,
        out_indices=[0, 1, 2, 3],`
![pretrained](https://user-images.githubusercontent.com/24259779/157836916-c2eeb144-00cb-446e-b4d7-3732d0be934c.png)

**Comment by jeethesh-pai** [comment]
how to train with pre-trained backbone say fo eg. convnext small ?
