### ISSUE TITLE
Speed of the convnext

### ISSUE THREAD

**Issue by shengkelong** [facebookresearch/ConvNeXt#83]
Hello, I recently tried to use the convnext structure for a task that attaches great importance to the inference speed (the faster the better, not a certain speed), the inference speed of convnext is more than twice as slow as 3*3 convolution, I Just use pytorch for inference, is there any way to improve the speed (can sacrifice a little precision), or if it is written using cudnn, will it narrow the gap with 3*3 convolution.

**Comment by shengkelong** [comment]
Sorry for the symbol problem. It's just the normal 3×3 conv for resnet。

**Comment by liuzhuang13** [comment]
which model architecture are you using for the 3x3 conv? Is it still in ConvNeXt or is it a resnet?

**Comment by shengkelong** [comment]
The traditional model is to use a 3×3 convolution resnet (without  bottleneck), which is not accurate but fast

**Comment by liuzhuang13** [comment]
We did observe ConvNeXt-Tiny is slower than ResNet-50 despite their flops are similar. This could be due to the relatively slower modules like depthwise convolutions, GELU, and LN in ConvNeXt. For larger models (e.g., ConvNeXt-B vs. ResNet-200) this discrepancy would be smaller.
