### ISSUE TITLE
my model_ema not updat

### ISSUE THREAD

**Issue by TAOSHss** [facebookresearch/ConvNeXt#85]
I turned on ema during training,But this operation doesn't seem to work。The model is updated normally, but the ema model is not updated with it.I don't know if I'm missing something.I have tried many times and the ema model will not update
![image](https://user-images.githubusercontent.com/44138279/160078626-a14d01e0-9d67-4beb-9ac9-ac43b85fea00.png)

**Comment by liuzhuang13** [comment]
Hi, 

Have you set --model_ema_eval to true as well? Can you share the exact command you run?

**Comment by TAOSHss** [comment]
> 

CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch  --nproc_per_node=2 train.py --model efficientnet_b0 --batch_size 512 --lr 2e-2 --update_freq 2  --data_path /data0/sihui3/mycode/rotateface/data/dataset/ --output_dir ./results/rotatex6 --nb_classes 4 --epochs 400 --input_size 112 --mixup 0 --cutmix 0  --clip_grad 0.1 --model_ema true --model_ema_eval true

**Comment by TAOSHss** [comment]
> Hi,
> 
> Have you set --model_ema_eval to true as well? Can you share the exact command you run?

CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch  --nproc_per_node=2 train.py --model efficientnet_b0 --batch_size 512 --lr 2e-2 --update_freq 2  --data_path data/dataset/ --output_dir ./results/rotatex6 --nb_classes 4 --epochs 400 --input_size 112 --mixup 0 --cutmix 0  --clip_grad 0.1 --model_ema true --model_ema_eval true

**Comment by liuzhuang13** [comment]
Not sure it is related to the efficientnet model you are using. We haven't tried Efficientnet with our training code. I think you may want to check the model passed into the ema evaluation function and see whether it is the same at every epoch

**Comment by jiyuanyu** [comment]
您好，请问我想测试自己的数据集，应该怎么修改代码？

**Comment by TAOSHss** [comment]
你只需要在在参数里把eval设置成true，数据集换成自己的数据集。看一下imagefolder，构建dataset的方式就行了。很简单



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 3, 2022 22:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/ConvNeXt] my model_ema not updat (Issue #85)




 
您好，请问我想测试自己的数据集，应该怎么修改代码？

**Comment by jiyuanyu** [comment]
好的，非常感谢您的解答。

**Comment by TAOSHss** [comment]
ok,i get it ,thanks.i like your training code ,so i tried other model on it.But WHAT I don't understand is why model_EMA can't be updated. Is it the model_EMA version problem?

---Original---
From: "Zhuang ***@***.***&gt;
Date: Fri, Mar 25, 2022 20:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/ConvNeXt] my model_ema not updat (Issue #85)




 
Not sure it is related to the efficientnet model you are using. We haven't tried Efficientnet with our training code. I think you may want to check the model passed into the ema evaluation function and see whether it is the same at every epoch

**Comment by jiyuanyu** [comment]
请问您有遇到这个错误吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/ConvNeXt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 晚上10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/ConvNeXt] my model_ema not updat (Issue #85)





 你只需要在在参数里把eval设置成true，数据集换成自己的数据集。看一下imagefolder，构建dataset的方式就行了。很简单 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Sun, Apr 3, 2022 22:10 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [facebookresearch/ConvNeXt] my model_ema not updat (Issue #85) 
 
 
 
 
   
 您好，请问我想测试自己的数据集，应该怎么修改代码？

**Comment by yxchng** [comment]
Have anyone of you found the problem? I also met this problem. It is quite weird.
