### ISSUE TITLE
What's the difference between model and model_ema?

### ISSUE THREAD

**Issue by leviome** [facebookresearch/ConvNeXt#88]
why we need ema? what is ema?

**Comment by liuzhuang13** [comment]
ema is sometimes useful in alleviate overfitting, especially on ImageNet-1K only training for large models. It is using the exponential moving average of weights instead of the current snapshot of weights. You can check the cited paper or the code for what it does.

**Comment by leviome** [comment]
"Exponential Moving Average", cool! thanks a lot!
