### ISSUE TITLE
The bug of resume/auto_resume

### ISSUE THREAD

**Issue by anonymoussss** [facebookresearch/ConvNeXt#94]
Hi，I find a bug in function 'resume' or 'auto_resume',

Whenever the args.resume or args.auto_resume are used, ‘max_acc’ and ‘max_acc_ema’  are reset to 0 (codes at the line 389 of main.py). However, when the first epoch of resuming training from the latest checkpoint ends, even if the acc_1 at this time is lower than the max_acc before, the previously saved checkpoint-best.pth or checkpoint-best-ema.pth will be overwritten. 

I think the max_accuracy and max_accuracy_ema parameter should be added to the saved checkpoint to update these two variables when resuming training.

**Comment by liuzhuang13** [comment]
Thank you for your suggestions! This indeed seemed like a bug for me, but we do find problems in distributed training using submitit for SLURM. I remember in distributed training, the program can save the previous variables and state, and reload from them so max_accuracy(_ema) is inherited but not saved as zero.
